shell = "zsh -c '{}'"
default-scheme = "base16-oceanicnext"

[[items]]
path = "~/projects/tinted-theming/tinted-terminal"
name = "tinted-alacritty"
themes-dir = "themes/alacritty"
supported-systems = ["base16", "base24"]

[[items]]
path = "~/projects/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux run 2> /dev/null && tmux source-file %f"
themes-dir = "colors"
supported-systems = ["base16", "base24"]

[[items]]
path = "~/projects/tinted-theming/tinted-vim"
name = "tinted-vim"
themes-dir = "colors"
supported-systems = ["base16", "base24"]
